// Command specsync vendors the response-side JSON-Schema closures from
// nanollm's pinned OpenAPI specs into go-mocklm's spec/ directory,
// together with the source sha256 pins. Run from the repo root:
//
//	go run ./cmd/specsync
//
// (also wired as `go generate ./...` via validator.go). The vendored
// output is deterministic: spec_sync_test.go re-runs the extraction and
// fails when the checked-in files drift from the pinned sources.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/viktordanov/go-mocklm/internal/specsync"
)

func main() {
	specDir := flag.String("spec-dir", "testdata/nanollm-spec", "directory holding the pinned openai-openapi.json / anthropic-openapi.json (defaults to the vendored in-repo copy; pass ../nanollm/spec to regen from a live nanollm checkout)")
	outDir := flag.String("out", "spec", "output directory for the vendored schema closures and pins")
	flag.Parse()

	openaiSrc, err := os.ReadFile(filepath.Join(*specDir, "openai-openapi.json"))
	if err != nil {
		log.Fatalf("reading OpenAI spec: %v", err)
	}
	anthropicSrc, err := os.ReadFile(filepath.Join(*specDir, "anthropic-openapi.json"))
	if err != nil {
		log.Fatalf("reading Anthropic spec: %v", err)
	}

	openai, err := specsync.ExtractOpenAI(openaiSrc)
	if err != nil {
		log.Fatalf("extracting OpenAI closure: %v", err)
	}
	anthropic, err := specsync.ExtractAnthropic(anthropicSrc)
	if err != nil {
		log.Fatalf("extracting Anthropic closure: %v", err)
	}

	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		log.Fatalf("creating %s: %v", *outDir, err)
	}
	write(filepath.Join(*outDir, "openai-responses.schema.json"), openai.Schema)
	write(filepath.Join(*outDir, "anthropic-responses.schema.json"), anthropic.Schema)

	pins := fmt.Sprintf(`{
  "$comment": "@generated by go run ./cmd/specsync — sha256 of the nanollm spec files the vendored closures were extracted from. spec_sync_test.go fails when these diverge from the vendored testdata/nanollm-spec pins.",
  "anthropic-openapi.json": %q,
  "openai-openapi.json": %q
}
`, anthropic.SourceSHA256, openai.SourceSHA256)
	write(filepath.Join(*outDir, "pins.json"), []byte(pins))

	fmt.Printf("openai:    %d schemas (roots %v) from sha256 %s\n",
		len(openai.Names), specsync.OpenAIRoots, openai.SourceSHA256[:12])
	fmt.Printf("anthropic: %d schemas (roots %v) from sha256 %s\n",
		len(anthropic.Names), specsync.AnthropicRoots, anthropic.SourceSHA256[:12])
}

func write(path string, data []byte) {
	if err := os.WriteFile(path, data, 0o644); err != nil {
		log.Fatalf("writing %s: %v", path, err)
	}
}
